// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar'];
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb'];
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem'];
    ADrawer: typeof import('ant-design-vue/es')['Drawer'];
    AMenu: typeof import('ant-design-vue/es')['Menu'];
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem'];
    AModal: typeof import('ant-design-vue/es')['Modal'];
    APopover: typeof import('ant-design-vue/es')['Popover'];
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu'];
    ConsoleRouter: typeof import('./../src/components/ConsoleRouter/index.vue')['default'];
    ContainerDrag: typeof import('./../src/components/ContainerDrag/index.vue')['default'];
    DzAlert: typeof import('./../src/components/DzAlert/index.vue')['default'];
    DzButton: typeof import('./../src/components/DzButton/index.vue')['default'];
    DzDataLayout: typeof import('./../src/components/DzDataLayout/index.vue')['default'];
    DzDivider: typeof import('./../src/components/DzDivider/index.vue')['default'];
    DzFont: typeof import('./../src/components/DzFont/index.vue')['default'];
    DzForm: typeof import('./../src/components/DzForm/index.vue')['default'];
    DzIcon: typeof import('./../src/components/DzIcon/index.vue')['default'];
    DzPageTable: typeof import('./../src/components/DzPageTable/index.vue')['default'];
    DzPagination: typeof import('./../src/components/DzPagination/index.vue')['default'];
    DzPopover: typeof import('./../src/components/DzPopover/index.vue')['default'];
    DzTable: typeof import('./../src/components/DzTable/index.vue')['default'];
    DzView: typeof import('./../src/components/DzView/index.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
