// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ConsoleRouter: typeof import('./../src/components/ConsoleRouter/index.vue')['default'];
    ConsoleRouterComponentsPaneListAll: typeof import('./../src/components/ConsoleRouter/components/PaneListAll/index.vue')['default'];
    ConsoleRouterComponentsPaneListSearch: typeof import('./../src/components/ConsoleRouter/components/PaneListSearch/index.vue')['default'];
    ConsoleRouterComponentsPaneSearch: typeof import('./../src/components/ConsoleRouter/components/PaneSearch/index.vue')['default'];
    ContainerDrag: typeof import('./../src/components/ContainerDrag/index.vue')['default'];
    FlexContainer: typeof import('./../src/components/FlexContainer/index.vue')['default'];
    LayoutContainer: typeof import('./../src/components/LayoutContainer/index.vue')['default'];
    PaneListAll: typeof import('./../src/components/ConsoleRouter/components/PaneListAll/index.vue')['default'];
    PaneListSearch: typeof import('./../src/components/ConsoleRouter/components/PaneListSearch/index.vue')['default'];
    PaneSearch: typeof import('./../src/components/ConsoleRouter/components/PaneSearch/index.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    TreeMenu: typeof import('./../src/components/TreeMenu/index.vue')['default'];
    TreeMenuComponentsTreeMenuItem: typeof import('./../src/components/TreeMenu/components/TreeMenuItem/index.vue')['default'];
    TreeMenuItem: typeof import('./../src/components/TreeMenu/components/TreeMenuItem/index.vue')['default'];
    ZIcon: typeof import('./../src/components/ZIcon/index.vue')['default'];
  }
}
