// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATreeSelect: typeof import('ant-design-vue/es')['TreeSelect']
    ConsoleRouter: typeof import('./../src/components/ConsoleRouter/index.vue')['default']
    ContainerDrag: typeof import('./../src/components/ContainerDrag/index.vue')['default']
    DzAlert: typeof import('./../src/components/DzAlert/index.vue')['default']
    DzButton: typeof import('./../src/components/DzButton/index.vue')['default']
    DzDataLayout: typeof import('./../src/components/DzDataLayout/index.vue')['default']
    DzDivider: typeof import('./../src/components/DzDivider/index.vue')['default']
    DzFont: typeof import('./../src/components/DzFont/index.vue')['default']
    DzForm: typeof import('./../src/components/DzForm/index.vue')['default']
    DzFormItem: typeof import('./../src/components/DzFormItem/index.vue')['default']
    DzIcon: typeof import('./../src/components/DzIcon/index.vue')['default']
    DzModal: typeof import('./../src/components/DzModal/index.vue')['default']
    DzPageTable: typeof import('./../src/components/DzPageTable/index.vue')['default']
    DzPagination: typeof import('./../src/components/DzPagination/index.vue')['default']
    DzPopover: typeof import('./../src/components/DzPopover/index.vue')['default']
    DzTable: typeof import('./../src/components/DzTable/index.vue')['default']
    DzView: typeof import('./../src/components/DzView/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TForm: typeof import('./../src/components/TForm/index.vue')['default']
    TForm2: typeof import('./../src/components/TForm2/index.vue')['default']
  }
}
