export default [
  {
    id: 'Three',
    code: 'Three',
    scope: 'Three',
    component: '',
    icon: 'ic:twotone-yard',
    redirct: '',
    target: '_self',
    url: '',
    showMenu: true,
    parentId: '',
    parentCode: '',
    path: 'Three',
  },
  {
    id: 'ThreeCustom',
    code: 'ThreeCustom',
    scope: 'Three',
    component: '',
    icon: 'ic:twotone-yard',
    redirct: '',
    target: '_self',
    url: '',
    showMenu: true,
    parentId: '',
    parentCode: '',
    path: 'ThreeCustom',
  },
  {
    id: 'Demo',
    code: 'Demo',
    scope: 'Three',
    component: '',
    icon: 'ic:twotone-yard',
    redirct: '',
    target: '_self',
    url: '',
    showMenu: true,
    parentId: 'ThreeCustom',
    parentCode: '',
    path: 'ThreeCustom,Demo',
  },
  {
    id: 'Demo/Alert',
    code: 'Demo/Alert',
    scope: 'Three',
    component: 'Demo/Alert',
    icon: 'ic:twotone-yard',
    redirct: '/Demo/Alert',
    target: '_self',
    url: '',
    showMenu: true,
    parentId: 'Demo',
    parentCode: 'Demo',
    path: 'ThreeCustom,Demo,Demo/Alert',
  },
  {
    id: 'Demo/Button',
    code: 'Demo/Button',
    scope: 'Three',
    component: 'Demo/Button',
    icon: 'ic:twotone-yard',
    redirct: '/Demo/Button',
    target: '_self',
    url: '',
    showMenu: true,
    parentId: 'ThreeCustom',
    parentCode: 'ThreeCustom',
    path: 'ThreeCustom,Demo/Button',
  },
  {
    id: 'Demo/Exception403',
    code: 'Demo/Exception403',
    scope: 'Three',
    component: 'Demo/Exception403',
    icon: 'ic:twotone-yard',
    redirct: '/Demo/Exception403',
    target: '_self',
    url: '',
    showMenu: true,
    parentId: 'ThreeCustom',
    parentCode: 'ThreeCustom',
    path: 'ThreeCustom,Demo/Exception403',
  },
  {
    id: 'Demo/Exception404',
    code: 'Demo/Exception404',
    scope: 'Three',
    component: 'Demo/Exception404',
    icon: 'ic:twotone-yard',
    redirct: '/Demo/Exception404',
    target: '_self',
    url: '',
    showMenu: true,
    parentId: 'ThreeCustom',
    parentCode: 'ThreeCustom',
    path: 'ThreeCustom,Demo/Exception404',
  },
  {
    id: 'Demo/Exception500',
    code: 'Demo/Exception500',
    scope: 'Three',
    component: 'Demo/Exception500',
    icon: 'ic:twotone-yard',
    redirct: '/Demo/Exception500',
    target: '_self',
    url: '',
    showMenu: true,
    parentId: 'ThreeCustom',
    parentCode: 'ThreeCustom',
    path: 'ThreeCustom,Demo/Exception500',
  },
  {
    id: 'Demo/ExceptionNetwork',
    code: 'Demo/ExceptionNetwork',
    scope: 'Three',
    component: 'Demo/ExceptionNetwork',
    icon: 'ic:twotone-yard',
    redirct: '/Demo/ExceptionNetwork',
    target: '_self',
    url: '',
    showMenu: true,
    parentId: 'ThreeCustom',
    parentCode: 'ThreeCustom',
    path: 'ThreeCustom,Demo/ExceptionNetwork',
  },
  {
    id: 'Demo/ExceptionNoData',
    code: 'Demo/ExceptionNoData',
    scope: 'Three',
    component: 'Demo/ExceptionNoData',
    icon: 'ic:twotone-yard',
    redirct: '/Demo/ExceptionNoData',
    target: '_self',
    url: '',
    showMenu: true,
    parentId: 'ThreeCustom',
    parentCode: 'ThreeCustom',
    path: 'ThreeCustom,Demo/ExceptionNoData',
  },
  {
    id: 'Demo/ExceptionWait',
    code: 'Demo/ExceptionWait',
    scope: 'Three',
    component: 'Demo/ExceptionWait',
    icon: 'ic:twotone-yard',
    redirct: '/Demo/ExceptionWait',
    target: '_self',
    url: '',
    showMenu: true,
    parentId: 'ThreeCustom',
    parentCode: 'ThreeCustom',
    path: 'ThreeCustom,Demo/ExceptionWait',
  },
  {
    id: 'Demo/Form',
    code: 'Demo/Form',
    scope: 'Three',
    component: 'Demo/Form',
    icon: 'ic:twotone-yard',
    redirct: '/Demo/Form',
    target: '_self',
    url: '',
    showMenu: true,
    parentId: 'ThreeCustom',
    parentCode: 'ThreeCustom',
    path: 'ThreeCustom,Demo/Form',
  },
];
